apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: argocd  # Make sure this matches your namespace
spec:
  selector:
    app: my-app  # This should match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80  # The port exposed within the cluster
      targetPort: 80  # The port on which the container is running
  type: LoadBalancer  # Change to LoadBalancer or NodePort if external access is required